@startuml
skinparam {
    BoundaryBackgroundColor #629EF9
    BoundaryBorderColor black
    BoundaryFontSize 12
    BoundarySize 10
    ControlBackgroundColor #b5bd68
    ControlBorderColor #718c00
    EntityBackgroundColor #F2AC4E
    EntityBorderColor black
    ArrowColor black
}

hide stereotype
skinparam class {
    BorderColor<<new>> green
}

package mastermind {

abstract class Mastermind
class ConsoleMastermind

package controllers {
    class Controller
    class StateController <<new>>
    class Logic {
    }
    class ProposeCombinationController{
    }
    class StartController{
    }
}
package models {
    class Game

    class State <<new>>
    class StateValue <<new>>
}

package views {

    Abstract View {
        interact(Controller controller)
    }

    class ConsoleView

    package console{
        class StartView
        class ProposedCombinationView
        class GameView
}



}

Mastermind *-- View
Mastermind *---- Logic
Mastermind <|-up- ConsoleMastermind
View <|-- ConsoleView
View ..> Controller
ConsoleView .[#red].> StartController
ConsoleView .[#red].> ProposeCombinationController

Logic *-- Game
Logic *-[#green]- State : currentState
Logic *-[#green]- "*" StateController
StateController *-[#green]- Controller
StateController *-[#green]- State

ConsoleView *-- GameView
ConsoleView *-- StartView

GameView *-- ProposedCombinationView
GameView ..> ProposeCombinationController
StartView ..> StartController
ProposedCombinationView ..> ProposeCombinationController
Controller <|-- StartController
Controller <|-- ProposeCombinationController
Controller --> Game
Controller -[#green]--> State
State *-- StateValue
}


@enduml