@startuml
skinparam {
    BoundaryBackgroundColor #629EF9
    BoundaryBorderColor black
    BoundaryFontSize 12
    BoundarySize 10
    ControlBackgroundColor #b5bd68
    ControlBorderColor #718c00
    EntityBackgroundColor #F2AC4E
    EntityBorderColor black
    ArrowColor black

}

package mastermind {

abstract class Mastermind
class ConsoleMastermind

package controllers {
    class Controller
    class Logic {
        <color:red>playCombination()
        <color:red>initGame()
    }
    class ProposeCombinationController{
            <color:red>playCombination()
    }
    class ResumeController
    class StartController{
    <color:red>initGame()
    }
}

package models {
    class Game
}

package views {

    class View
    class ConsoleView

    package console{
        class StartView
        class ProposedCombinationView
        class GameView
}



}

Mastermind *-- View
Mastermind *---[#green]- Logic
Mastermind <|-up- ConsoleMastermind
View <|-- ConsoleView
View -[#green]-> Logic
Logic *-- Game
Logic *-[#green]-- ProposeCombinationController
Logic *-[#green]-- ResumeController
Logic *-[#green]-- StartController

ConsoleView *-- GameView
ConsoleView *-- StartView

GameView *-- ProposedCombinationView
GameView --> Logic
StartView --> Logic
ProposedCombinationView --> Logic
Controller <|-- StartController
Controller <|-- ResumeController
Controller <|-- ProposeCombinationController


}


@enduml